var searchData=
[
  ['uilanguages',['uiLanguages',['https://doc.qt.io/qt-5/qlocale.html#uiLanguages',1,'QLocale']]],
  ['unavailable',['unavailable',['../classQDiscordGuild.html#a3860ec126d4b6d95f3531beddae9e72a',1,'QDiscordGuild']]],
  ['unblock',['unblock',['https://doc.qt.io/qt-5/qsignalblocker.html#unblock',1,'QSignalBlocker']]],
  ['ungetchar',['ungetChar',['https://doc.qt.io/qt-5/qiodevice.html#ungetChar',1,'QIODevice']]],
  ['unicode',['unicode',['https://doc.qt.io/qt-5/qlatin1char.html#unicode',1,'QLatin1Char::unicode()'],['https://doc.qt.io/qt-5/qchar.html#unicode',1,'QChar::unicode() const'],['https://doc.qt.io/qt-5/qchar.html#unicode-1',1,'QChar::unicode()'],['https://doc.qt.io/qt-5/qstring.html#unicode',1,'QString::unicode()'],['https://doc.qt.io/qt-5/qstringref.html#unicode',1,'QStringRef::unicode()']]],
  ['unicodeversion',['unicodeVersion',['https://doc.qt.io/qt-5/qchar.html#unicodeVersion',1,'QChar::unicodeVersion() const'],['https://doc.qt.io/qt-5/qchar.html#unicodeVersion-1',1,'QChar::unicodeVersion(uint ucs4)']]],
  ['uniquekeys',['uniqueKeys',['https://doc.qt.io/qt-5/qhash.html#uniqueKeys',1,'QHash::uniqueKeys()'],['https://doc.qt.io/qt-5/qmap.html#uniqueKeys',1,'QMap::uniqueKeys()']]],
  ['unite',['unite',['https://doc.qt.io/qt-5/qhash.html#unite',1,'QHash::unite()'],['https://doc.qt.io/qt-5/qmap.html#unite',1,'QMap::unite()'],['https://doc.qt.io/qt-5/qrect-obsolete.html#unite',1,'QRect::unite()'],['https://doc.qt.io/qt-5/qrectf-obsolete.html#unite',1,'QRectF::unite()'],['https://doc.qt.io/qt-5/qset.html#unite',1,'QSet::unite()']]],
  ['united',['united',['https://doc.qt.io/qt-5/qrect.html#united',1,'QRect::united()'],['https://doc.qt.io/qt-5/qrectf.html#united',1,'QRectF::united()']]],
  ['unitvector',['unitVector',['https://doc.qt.io/qt-5/qlinef.html#unitVector',1,'QLineF']]],
  ['unknownoptionnames',['unknownOptionNames',['https://doc.qt.io/qt-5/qcommandlineparser.html#unknownOptionNames',1,'QCommandLineParser']]],
  ['unload',['unload',['https://doc.qt.io/qt-5/qlibrary.html#unload',1,'QLibrary::unload()'],['https://doc.qt.io/qt-5/qpluginloader.html#unload',1,'QPluginLoader::unload()']]],
  ['unlock',['unlock',['https://doc.qt.io/qt-5/qlockfile.html#unlock',1,'QLockFile::unlock()'],['https://doc.qt.io/qt-5/qsharedmemory.html#unlock',1,'QSharedMemory::unlock()'],['https://doc.qt.io/qt-5/qmutex.html#unlock',1,'QMutex::unlock()'],['https://doc.qt.io/qt-5/qmutexlocker.html#unlock',1,'QMutexLocker::unlock()'],['https://doc.qt.io/qt-5/qreadwritelock.html#unlock',1,'QReadWriteLock::unlock()'],['https://doc.qt.io/qt-5/qreadlocker.html#unlock',1,'QReadLocker::unlock()'],['https://doc.qt.io/qt-5/qwritelocker.html#unlock',1,'QWriteLocker::unlock()']]],
  ['unmap',['unmap',['https://doc.qt.io/qt-5/qfiledevice.html#unmap',1,'QFileDevice']]],
  ['unregistereventnotifier',['unregisterEventNotifier',['https://doc.qt.io/qt-5/qabstracteventdispatcher.html#unregisterEventNotifier',1,'QAbstractEventDispatcher']]],
  ['unregisterresource',['unregisterResource',['https://doc.qt.io/qt-5/qresource.html#unregisterResource',1,'QResource::unregisterResource(const QString &amp;rccFileName, const QString &amp;mapRoot)'],['https://doc.qt.io/qt-5/qresource.html#unregisterResource-1',1,'QResource::unregisterResource(const uchar *rccData, const QString &amp;mapRoot)']]],
  ['unregistersocketnotifier',['unregisterSocketNotifier',['https://doc.qt.io/qt-5/qabstracteventdispatcher.html#unregisterSocketNotifier',1,'QAbstractEventDispatcher']]],
  ['unregistertimer',['unregisterTimer',['https://doc.qt.io/qt-5/qabstracteventdispatcher.html#unregisterTimer',1,'QAbstractEventDispatcher']]],
  ['unregistertimers',['unregisterTimers',['https://doc.qt.io/qt-5/qabstracteventdispatcher.html#unregisterTimers',1,'QAbstractEventDispatcher']]],
  ['unsetdevice',['unsetDevice',['https://doc.qt.io/qt-5/qdatastream-obsolete.html#unsetDevice',1,'QDataStream']]],
  ['unseterror',['unsetError',['https://doc.qt.io/qt-5/qfiledevice.html#unsetError',1,'QFileDevice']]],
  ['update',['update',['../classQDiscordMember.html#a12dd18f358c6bb1a9587df9159a90c8b',1,'QDiscordMember::update()'],['../classQDiscordUser.html#a07fe1d3d30538eed77a35cf14a98e005',1,'QDiscordUser::update()']]],
  ['updatecompleted',['updateCompleted',['https://doc.qt.io/qt-5/qnetworkconfigurationmanager.html#updateCompleted',1,'QNetworkConfigurationManager']]],
  ['updateconfigurations',['updateConfigurations',['https://doc.qt.io/qt-5/qnetworkconfigurationmanager.html#updateConfigurations',1,'QNetworkConfigurationManager']]],
  ['updatecookie',['updateCookie',['https://doc.qt.io/qt-5/qnetworkcookiejar.html#updateCookie',1,'QNetworkCookieJar']]],
  ['updatecurrenttime',['updateCurrentTime',['https://doc.qt.io/qt-5/qabstractanimation.html#updateCurrentTime',1,'QAbstractAnimation::updateCurrentTime()'],['https://doc.qt.io/qt-5/qparallelanimationgroup.html#updateCurrentTime',1,'QParallelAnimationGroup::updateCurrentTime()'],['https://doc.qt.io/qt-5/qpauseanimation.html#updateCurrentTime',1,'QPauseAnimation::updateCurrentTime()'],['https://doc.qt.io/qt-5/qsequentialanimationgroup.html#updateCurrentTime',1,'QSequentialAnimationGroup::updateCurrentTime()'],['https://doc.qt.io/qt-5/qvariantanimation.html#updateCurrentTime',1,'QVariantAnimation::updateCurrentTime()']]],
  ['updatecurrentvalue',['updateCurrentValue',['https://doc.qt.io/qt-5/qpropertyanimation.html#updateCurrentValue',1,'QPropertyAnimation::updateCurrentValue()'],['https://doc.qt.io/qt-5/qvariantanimation.html#updateCurrentValue',1,'QVariantAnimation::updateCurrentValue()']]],
  ['updatedirection',['updateDirection',['https://doc.qt.io/qt-5/qabstractanimation.html#updateDirection',1,'QAbstractAnimation::updateDirection()'],['https://doc.qt.io/qt-5/qparallelanimationgroup.html#updateDirection',1,'QParallelAnimationGroup::updateDirection()'],['https://doc.qt.io/qt-5/qsequentialanimationgroup.html#updateDirection',1,'QSequentialAnimationGroup::updateDirection()']]],
  ['updateinterval',['updateInterval',['https://doc.qt.io/qt-5/qtimeline.html#updateInterval-prop',1,'QTimeLine']]],
  ['updatemetadata',['updateMetaData',['https://doc.qt.io/qt-5/qabstractnetworkcache.html#updateMetaData',1,'QAbstractNetworkCache::updateMetaData()'],['https://doc.qt.io/qt-5/qnetworkdiskcache.html#updateMetaData',1,'QNetworkDiskCache::updateMetaData()']]],
  ['updatestate',['updateState',['https://doc.qt.io/qt-5/qabstractanimation.html#updateState',1,'QAbstractAnimation::updateState()'],['https://doc.qt.io/qt-5/qparallelanimationgroup.html#updateState',1,'QParallelAnimationGroup::updateState()'],['https://doc.qt.io/qt-5/qpropertyanimation.html#updateState',1,'QPropertyAnimation::updateState()'],['https://doc.qt.io/qt-5/qsequentialanimationgroup.html#updateState',1,'QSequentialAnimationGroup::updateState()'],['https://doc.qt.io/qt-5/qvariantanimation.html#updateState',1,'QVariantAnimation::updateState()']]],
  ['uploadprogress',['uploadProgress',['https://doc.qt.io/qt-5/qnetworkreply.html#uploadProgress',1,'QNetworkReply']]],
  ['upperbound',['upperBound',['https://doc.qt.io/qt-5/qmap.html#upperBound',1,'QMap::upperBound(const Key &amp;key)'],['https://doc.qt.io/qt-5/qmap.html#upperBound-1',1,'QMap::upperBound(const Key &amp;key) const']]],
  ['url',['url',['https://doc.qt.io/qt-5/qurl.html#url',1,'QUrl::url()'],['https://doc.qt.io/qt-5/qnetworkcachemetadata.html#url',1,'QNetworkCacheMetaData::url()'],['https://doc.qt.io/qt-5/qnetworkreply.html#url',1,'QNetworkReply::url()'],['https://doc.qt.io/qt-5/qnetworkrequest.html#url',1,'QNetworkRequest::url()'],['https://doc.qt.io/qt-5/qnetworkproxyquery.html#url',1,'QNetworkProxyQuery::url()'],['../classQDiscordGame.html#a63f53ee5217314e929af7e34b7f3856a',1,'QDiscordGame::url()']]],
  ['urls',['urls',['https://doc.qt.io/qt-5/qmimedata.html#urls',1,'QMimeData']]],
  ['usagepolicies',['usagePolicies',['https://doc.qt.io/qt-5/qnetworksession.html#usagePolicies',1,'QNetworkSession']]],
  ['usagepolicieschanged',['usagePoliciesChanged',['https://doc.qt.io/qt-5/qnetworksession.html#usagePoliciesChanged',1,'QNetworkSession']]],
  ['usedbits',['usedBits',['https://doc.qt.io/qt-5/qsslcipher.html#usedBits',1,'QSslCipher']]],
  ['user',['user',['https://doc.qt.io/qt-5/qauthenticator.html#user',1,'QAuthenticator::user()'],['https://doc.qt.io/qt-5/qnetworkproxy.html#user',1,'QNetworkProxy::user()'],['../classQDiscordMember.html#a3d8dc8469cc98b3c57a595527718b242',1,'QDiscordMember::user()']]],
  ['userinfo',['userInfo',['https://doc.qt.io/qt-5/qurl.html#userInfo',1,'QUrl']]],
  ['username',['userName',['https://doc.qt.io/qt-5/qurl.html#userName',1,'QUrl::userName()'],['../classQDiscordUser.html#a41b9e736bf4a32fd2696a0381e9c1d92',1,'QDiscordUser::username()']]],
  ['userproperty',['userProperty',['https://doc.qt.io/qt-5/qmetaobject.html#userProperty',1,'QMetaObject']]],
  ['usertype',['userType',['https://doc.qt.io/qt-5/qmetaproperty.html#userType',1,'QMetaProperty::userType()'],['https://doc.qt.io/qt-5/qvariant.html#userType',1,'QVariant::userType()']]],
  ['usleep',['usleep',['https://doc.qt.io/qt-5/qthread.html#usleep',1,'QThread']]],
  ['utc',['utc',['https://doc.qt.io/qt-5/qtimezone.html#utc',1,'QTimeZone']]],
  ['utf16',['utf16',['https://doc.qt.io/qt-5/qstring.html#utf16',1,'QString']]]
];
